version: '0.0.0'
bandwidth-limits:
  upload: 1000 # 1 MB
  download: 1000
ip-rules:
  - ip: '172.217.5.110' # google.com
    protocol: 'tcp'
    port: '1:1024'
    behavior: 'drop'
    direction: 'to'
    log: 'true'
    logfile: 'iplog.txt'
hostname-rules:
  - host: 'qq.com'
    protocol: 'tcp'
    behavior: 'drop'
    direction: 'from'
    log: 'true'
    logfile: 'hostlog.txt'